// DO NOT EDIT -- Generated by format-registry-generator

use core::fmt;

/// 16-bit error identifier.
///
/// Every format-level error in an NWB archive is classified by one of
/// these discriminants.  The `Invalid` variant (0x0000) is reserved and
/// must not appear in valid diagnostic output.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
#[repr(u16)]
#[allow(clippy::upper_case_acronyms)]
pub enum ErrorId {
    /// Catalog data is corrupt or inconsistent.
    CatalogCorrupt = 0x0300,
    /// Data integrity verification failed.
    ChecksumMismatch = 0x0001,
    /// Compression or decompression error.
    Compression = 0x0003,
    /// Encryption authentication or decryption failure.
    EncryptionAuth = 0x0200,
    /// Unsupported or unrecognized format version.
    FormatVersion = 0x0002,
    /// Invalid/zero sentinel, must not appear in valid output.
    Invalid = 0x0000,
    /// Input/output operation failed.
    IoError = 0x0100,
    /// Segment data is corrupt or truncated.
    SegmentCorrupt = 0x0004,
    /// Required volume is not available.
    VolumeMissing = 0x0101,
}

impl fmt::Display for ErrorId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::CatalogCorrupt => "CatalogCorrupt",
                Self::ChecksumMismatch => "ChecksumMismatch",
                Self::Compression => "Compression",
                Self::EncryptionAuth => "EncryptionAuth",
                Self::FormatVersion => "FormatVersion",
                Self::Invalid => "Invalid",
                Self::IoError => "IoError",
                Self::SegmentCorrupt => "SegmentCorrupt",
                Self::VolumeMissing => "VolumeMissing",
            }
        )
    }
}
