// DO NOT EDIT -- Generated by format-registry-generator

//! Feature bit constants for the NWB format capability bitmask.
//!
//! Each constant defines a single bit position within a 64-bit feature mask
//! carried in the volume header.  A compile-time `const` block verifies that
//! no two constants share the same bit position.

// --- Bit-position constants (u8) ---

/// Bit position for Bare-metal recovery metadata present.
pub const BMR_METADATA: u8 = 4;

/// Bit position for Checkpoint/resume support.
pub const CHECKPOINT: u8 = 3;

/// Bit position for Zstandard compression.
pub const COMPRESSION_ZSTD: u8 = 0;

/// Bit position for AES-256-GCM encryption.
pub const ENCRYPTION_AES256_GCM: u8 = 1;

/// Bit position for Multi-volume set support.
pub const VOLUME_SET: u8 = 2;

// --- Compile-time uniqueness check ---
//
// Verifies that every allocated bit position maps to a distinct, valid bit
// in a u64 mask.  A duplicate, zero, or out-of-range position is caught
// before any code is generated.

const _: () = {
    const ALLOCATED: &[u8] = &[
        BMR_METADATA,
        CHECKPOINT,
        COMPRESSION_ZSTD,
        ENCRYPTION_AES256_GCM,
        VOLUME_SET,
    ];

    let mut mask: u64 = 0;
    let mut i: usize = 0;
    while i < ALLOCATED.len() {
        let pos = ALLOCATED[i];
        // Must be within valid bit range.
        assert!((pos as u64) < 64u64);
        let bit = 1u64 << pos;
        // Must not overlap with any previously seen bit.
        assert!(mask & bit == 0u64);
        mask |= bit;
        i += 1;
    }
};
