// DO NOT EDIT -- Generated by format-registry-generator

use core::fmt;

/// Type of backup contained in the archive.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
#[repr(u8)]
pub enum BackupKind {
    /// Differential backup: changes since last full backup.
    Differential = 2,
    /// Full backup: all selected data.
    Full = 1,
}

impl fmt::Display for BackupKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Differential => write!(f, "Differential"),
            Self::Full => write!(f, "Full"),
        }
    }
}

/// Originating platform hint carried in the volume header.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
#[repr(u8)]
pub enum PlatformHint {
    /// Linux.
    Linux = 2,
    /// Unknown or unspecified platform.
    Unknown = 0,
    /// Microsoft Windows.
    Windows = 1,
}

impl fmt::Display for PlatformHint {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Linux => write!(f, "Linux"),
            Self::Unknown => write!(f, "Unknown"),
            Self::Windows => write!(f, "Windows"),
        }
    }
}
