// DO NOT EDIT -- Generated by format-registry-generator

use core::fmt;

/// 16-bit record type discriminator.
///
/// Every physical record in an NWB archive begins with a record header that
/// contains one of these values.  The `Invalid` variant (0x0000) is reserved
/// and must never appear in a valid stream.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
#[repr(u16)]
#[allow(clippy::upper_case_acronyms)]
pub enum RecordType {
    /// BMR artifact: bare-metal recovery artifact (boot image, config, etc.).
    BmrArtifact = 0x0403,
    /// Catalog page: sorted index of backed-up items.
    CatalogPage = 0x0201,
    /// Chunk index page: mapping of chunk hashes to storage locations.
    ChunkIndexPage = 0x0202,
    /// Compressed/encrypted data chunk.
    DataChunk = 0x0101,
    /// Differential operation: binary diff patch.
    DiffOperation = 0x0106,
    /// Disk extent: contiguous sector range within a disk backup.
    DiskExtent = 0x0105,
    /// Error record: logged I/O or integrity fault within the archive.
    ErrorRecord = 0x0301,
    /// File entry: metadata for a single backed-up file.
    FileEntry = 0x0401,
    /// File extent: contiguous byte range within a file backup.
    FileExtent = 0x0104,
    /// Hole run (unallocated region descriptor).
    HoleRun = 0x0103,
    /// Invalid/zero sentinel — reserved, must not appear in valid streams.
    Invalid = 0x0000,
    /// Key slot: encrypted key material for envelope encryption.
    KeySlot = 0x0501,
    /// Volume manifest: metadata about the current physical volume.
    Manifest = 0x0001,
    /// Partition layout: partition table snapshot.
    PartitionLayout = 0x0402,
    /// Tombstone: marks a removed or voided record slot.
    Tombstone = 0x0004,
    /// Volume footer: final record sealing the volume.
    VolumeFooter = 0x0003,
    /// Volume set manifest: linkage across a multi-volume archive.
    VolumeSetManifest = 0x0002,
    /// Zero-byte run (sparse region descriptor).
    ZeroRun = 0x0102,
}

impl fmt::Display for RecordType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::BmrArtifact => "BmrArtifact",
                Self::CatalogPage => "CatalogPage",
                Self::ChunkIndexPage => "ChunkIndexPage",
                Self::DataChunk => "DataChunk",
                Self::DiffOperation => "DiffOperation",
                Self::DiskExtent => "DiskExtent",
                Self::ErrorRecord => "ErrorRecord",
                Self::FileEntry => "FileEntry",
                Self::FileExtent => "FileExtent",
                Self::HoleRun => "HoleRun",
                Self::Invalid => "Invalid",
                Self::KeySlot => "KeySlot",
                Self::Manifest => "Manifest",
                Self::PartitionLayout => "PartitionLayout",
                Self::Tombstone => "Tombstone",
                Self::VolumeFooter => "VolumeFooter",
                Self::VolumeSetManifest => "VolumeSetManifest",
                Self::ZeroRun => "ZeroRun",
            }
        )
    }
}
