#![allow(dead_code)]

//! Rust source code generation from parsed registry data.

use crate::parser::{DiscriminantRegistry, ParsedRegistry};
use crate::schema::{BitEntry, DiscriminantEntry, EnumDef};

const GENERATED_HEADER: &str = "// DO NOT EDIT -- Generated by format-registry-generator\n";

// ---------------------------------------------------------------------------
// Top-level generation dispatch
// ---------------------------------------------------------------------------

/// Generate a Rust source string from a parsed registry.
pub fn generate(registry: &ParsedRegistry) -> String {
    match registry {
        ParsedRegistry::Discriminant(dr) => generate_discriminant(dr),
        ParsedRegistry::Bit(entries) => generate_bit(entries),
        ParsedRegistry::EnumSet(enums) => generate_enum_set(enums),
    }
}

// ---------------------------------------------------------------------------
// Discriminant generation (RecordType, ErrorId)
// ---------------------------------------------------------------------------

fn generate_discriminant(reg: &DiscriminantRegistry) -> String {
    let repr = "u16";
    let enum_name = &reg.enum_name;
    let entries = &reg.entries;

    let header_doc = if enum_name == "RecordType" {
        String::from(
            "/// 16-bit record type discriminator.\n\
             ///\n\
             /// Every physical record in an NWB archive begins with a record header that\n\
             /// contains one of these values.  The `Invalid` variant (0x0000) is reserved\n\
             /// and must never appear in a valid stream.",
        )
    } else {
        String::from(
            "/// 16-bit error identifier.\n\
             ///\n\
             /// Every format-level error in an NWB archive is classified by one of\n\
             /// these discriminants.  The `Invalid` variant (0x0000) is reserved and\n\
             /// must not appear in valid diagnostic output.",
        )
    };

    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("\nuse core::fmt;\n\n");
    out.push_str(&header_doc);
    out.push_str("\n#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\n");
    out.push_str(&format!("#[repr({repr})]\n"));
    out.push_str("#[allow(clippy::upper_case_acronyms)]\n");
    out.push_str(&format!("pub enum {enum_name} {{\n"));

    for e in entries {
        let rust_name = &e.rust_name;
        let val_hex = format!("0x{:04X}", e.value);
        let desc = &e.description;
        out.push_str(&format!("    /// {desc}.\n"));
        out.push_str(&format!("    {rust_name} = {val_hex},\n"));
    }

    out.push_str("}\n\n");
    out.push_str(&generate_display_discriminant(enum_name, entries));
    out
}

fn generate_display_discriminant(enum_name: &str, entries: &[DiscriminantEntry]) -> String {
    let mut out = String::new();
    out.push_str(&format!("impl fmt::Display for {enum_name} {{\n"));
    out.push_str("    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {\n");
    out.push_str("        write!(\n");
    out.push_str("            f,\n");
    out.push_str("            \"{}\",\n");
    out.push_str("            match self {\n");

    for e in entries {
        let rust_name = &e.rust_name;
        out.push_str(&format!(
            "                Self::{rust_name} => \"{rust_name}\",\n"
        ));
    }

    out.push_str("            }\n");
    out.push_str("        )\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

// ---------------------------------------------------------------------------
// Bit generation (FeatureBit)
// ---------------------------------------------------------------------------

fn generate_bit(entries: &[BitEntry]) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str(
        "\n\
         //! Feature bit constants for the NWB format capability bitmask.\n\
         //!\n\
         //! Each constant defines a single bit position within a 64-bit feature mask\n\
         //! carried in the volume header.  A compile-time `const` block verifies that\n\
         //! no two constants share the same bit position.\n\
         ",
    );

    out.push_str("\n// --- Bit-position constants (u8) ---\n\n");

    for e in entries {
        let rust_name = &e.rust_name;
        let bit = e.bit;
        let desc = &e.description;
        out.push_str(&format!("/// Bit position for {desc}.\n"));
        out.push_str(&format!("pub const {rust_name}: u8 = {bit};\n\n"));
    }

    out.push_str("// --- Compile-time uniqueness check ---\n");
    out.push_str("//\n");
    out.push_str("// Verifies that every allocated bit position maps to a distinct, valid bit\n");
    out.push_str("// in a u64 mask.  A duplicate, zero, or out-of-range position is caught\n");
    out.push_str("// before any code is generated.\n\n");
    out.push_str("const _: () = {\n");
    out.push_str("    const ALLOCATED: &[u8] = &[\n");

    for e in entries {
        out.push_str(&format!("        {},\n", e.rust_name));
    }

    out.push_str("    ];\n\n");
    out.push_str("    let mut mask: u64 = 0;\n");
    out.push_str("    let mut i: usize = 0;\n");
    out.push_str("    while i < ALLOCATED.len() {\n");
    out.push_str("        let pos = ALLOCATED[i];\n");
    out.push_str("        // Must be within valid bit range.\n");
    out.push_str("        assert!((pos as u64) < 64u64);\n");
    out.push_str("        let bit = 1u64 << pos;\n");
    out.push_str("        // Must not overlap with any previously seen bit.\n");
    out.push_str("        assert!(mask & bit == 0u64);\n");
    out.push_str("        mask |= bit;\n");
    out.push_str("        i += 1;\n");
    out.push_str("    }\n");
    out.push_str("};\n");

    out
}

// ---------------------------------------------------------------------------
// Enum set generation (BackupKind, PlatformHint)
// ---------------------------------------------------------------------------

fn generate_enum_set(enums: &[EnumDef]) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("\nuse core::fmt;\n");

    for def in enums {
        let rust_name = &def.rust_name;
        let repr = &def.repr;

        out.push_str(&format!("\n/// {}.\n", description_for_enum(rust_name)));
        out.push_str("#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\n");
        out.push_str(&format!("#[repr({repr})]\n"));
        out.push_str(&format!("pub enum {rust_name} {{\n"));

        for v in &def.entries {
            let var_name = &v.rust_name;
            let val = v.value;
            let desc = &v.description;
            out.push_str(&format!("    /// {desc}.\n"));
            out.push_str(&format!("    {var_name} = {val},\n"));
        }

        out.push_str("}\n");

        out.push_str(&format!("\nimpl fmt::Display for {rust_name} {{\n"));
        out.push_str("    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {\n");
        out.push_str("        match self {\n");
        for v in &def.entries {
            out.push_str(&format!(
                "            Self::{} => write!(f, \"{}\"),\n",
                v.rust_name, v.rust_name
            ));
        }
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("}\n");
    }

    out
}

fn description_for_enum(name: &str) -> &str {
    match name {
        "BackupKind" => "Type of backup contained in the archive",
        "PlatformHint" => "Originating platform hint carried in the volume header",
        _ => "",
    }
}
